const galleryImages = Array.from({length:38},(_,i)=>`assets/images/villa/villa-${i+1}.jpg`);
// Start with the Airbnb cover image, then include every listing photo.
galleryImages.unshift(galleryImages.splice(29,1)[0]);
galleryImages.splice(1,0,...["1933","2028","2024","2031","0604","2071","2074","2058","2019"].map(number=>`assets/images/villa/house-${number}.jpg`));
const track=document.querySelector("#gallery-track");
galleryImages.forEach((src,i)=>{const item=document.createElement("div");item.className="gallery-slide";item.innerHTML=`<img src="${src}" alt="Brienz Villa photo ${i+1} of ${galleryImages.length}" loading="${i<2?"eager":"lazy"}"><span>${String(i+1).padStart(2,"0")} · Brienz Villa</span>`;item.addEventListener("click",()=>openGallery(i));track.append(item)});
let galleryIndex=0;
const galleryCount=document.querySelector("#gallery-count");
function scrollGallery(direction){const slides=[...track.children];galleryIndex=Math.max(0,Math.min(slides.length-1,galleryIndex+direction));slides[galleryIndex].scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"});galleryCount.textContent=`${String(galleryIndex+1).padStart(2,"0")} / ${galleryImages.length}`}
document.querySelector("#gallery-prev").onclick=()=>scrollGallery(-1);document.querySelector("#gallery-next").onclick=()=>scrollGallery(1);
track.addEventListener("scroll",()=>{const slides=[...track.children],center=track.scrollLeft+track.clientWidth/2;let closest=0,d=Infinity;slides.forEach((el,i)=>{const x=el.offsetLeft+el.clientWidth/2;if(Math.abs(center-x)<d){d=Math.abs(center-x);closest=i}});galleryIndex=closest;galleryCount.textContent=`${String(closest+1).padStart(2,"0")} / ${galleryImages.length}`},{passive:true});
const galleryDialog=document.querySelector("#gallery-dialog"),dialogImage=document.querySelector("#dialog-image"),dialogCount=document.querySelector("#dialog-count");
function openGallery(index){galleryIndex=index;dialogImage.src=galleryImages[index];dialogImage.alt=`Brienz Villa photo ${index+1} of ${galleryImages.length}`;dialogCount.textContent=`${String(index+1).padStart(2,"0")} / ${galleryImages.length}`;galleryDialog.showModal()}
function dialogMove(n){galleryIndex=(galleryIndex+n+galleryImages.length)%galleryImages.length;openGalleryImage()}
function openGalleryImage(){dialogImage.src=galleryImages[galleryIndex];dialogImage.alt=`Brienz Villa photo ${galleryIndex+1} of ${galleryImages.length}`;dialogCount.textContent=`${String(galleryIndex+1).padStart(2,"0")} / ${galleryImages.length}`}
document.querySelector("#view-all").onclick=()=>openGallery(0);galleryDialog.querySelector(".dialog-close").onclick=()=>galleryDialog.close();galleryDialog.querySelector(".prev").onclick=()=>dialogMove(-1);galleryDialog.querySelector(".next").onclick=()=>dialogMove(1);
galleryDialog.addEventListener("click",e=>{if(e.target===galleryDialog)galleryDialog.close()});
const grid=document.querySelector("#outings-grid"),empty=document.querySelector("#empty-state"),search=document.querySelector("#outing-search"),sort=document.querySelector("#outing-sort"),filters=document.querySelector("#filter-buttons");let activeFilter="all";
const recommendedOrder=["brienz-rothorn-railway","lake-brienz-by-boat","jungfraujoch-top-of-europe","interlaken-day-trip","activities-for-kids","murren-allmendhubel-loop","eigergletscher-to-wengen","lucerne-day-trip","bern-day-trip","rosenlaui-to-grosse-scheidegg","harder-kulm-loop","first-to-bachalpsee","schynige-platte","gruyeres-day-trip","mannlichen-to-kleine-scheidegg","aare-gorge-reichenbach-falls","grutschalp-allmendhubel-murren","axalp-wooden-statue-loop","ballenberg-open-air-museum","giessbach-falls-to-iseltwald","brienz-to-planalp","eigergletscher-to-alpiglen","grosse-scheidegg-to-first","brienz-rothorn","brienz-rothorn-to-brunig-pass","axalp-giant-swing","bramisegg-to-axalp","schrattenflue-hangst"];
const recommendedRank=new Map(recommendedOrder.map((id,index)=>[id,index]));
function renderOutings(){const query=search.value.toLowerCase().trim();let items=OUTINGS.filter(o=>(activeFilter==="all"||o.tags.includes(activeFilter))&&`${o.title} ${o.description} ${o.badge}`.toLowerCase().includes(query));if(sort.value==="recommended")items.sort((a,b)=>(recommendedRank.get(a.id)??recommendedOrder.length)-(recommendedRank.get(b.id)??recommendedOrder.length));if(sort.value==="easy")items.sort((a,b)=>(a.difficulty??99)-(b.difficulty??99));if(sort.value==="duration")items.sort((a,b)=>(a.duration??99)-(b.duration??99));grid.innerHTML="";items.forEach(o=>{const card=document.createElement("article");card.className="outing-card";card.tabIndex=0;const meta=o.type==="excursion"?`<span>Day trip</span><span>${o.season}</span>`:`<span>${"●".repeat(o.difficulty)}${"○".repeat(4-o.difficulty)} · level ${o.difficulty}</span><span>${o.duration} hours</span>`;card.innerHTML=`<div class="outing-image"><img src="${o.image}" alt="${o.title}" loading="lazy"><span>${o.badge}</span></div><h3>${o.title}</h3><div class="outing-meta">${meta}</div>`;const activate=()=>o.page?location.href=o.page:openOuting(o);card.onclick=activate;card.onkeydown=e=>{if(e.key==="Enter")activate()};grid.append(card)});empty.hidden=items.length>0}
filters.onclick=e=>{if(!e.target.matches("button"))return;filters.querySelectorAll("button").forEach(b=>b.classList.remove("active"));e.target.classList.add("active");activeFilter=e.target.dataset.filter;renderOutings()};search.oninput=renderOutings;sort.onchange=renderOutings;renderOutings();
const outingDialog=document.querySelector("#outing-dialog"),outingDetail=document.querySelector("#outing-detail");
function openOuting(o){outingDetail.innerHTML=`<img class="outing-detail-image" src="${o.image}" alt="${o.title}"><div class="outing-detail-copy"><p class="eyebrow">${o.badge}</p><h2>${o.title}</h2><p class="lead">${o.description}</p><div class="detail-stats"><div><b>${o.distance}</b>Distance</div><div><b>${o.duration} hrs</b>Duration</div><div><b>${o.ascent}</b>Ascent</div><div><b>${o.season}</b>Season</div></div><div class="route"><b>Suggested itinerary</b>${o.route}</div><a class="button dark" href="${o.map}" target="_blank" rel="noopener">Open map & directions ↗</a></div>`;outingDialog.showModal()}
outingDialog.querySelector(".dialog-close").onclick=()=>outingDialog.close();outingDialog.addEventListener("click",e=>{if(e.target===outingDialog)outingDialog.close()});
document.querySelector(".nav-toggle").onclick=e=>{const h=document.querySelector(".site-header");h.classList.toggle("open");e.currentTarget.setAttribute("aria-expanded",h.classList.contains("open"))};document.querySelectorAll(".site-header nav a").forEach(a=>a.onclick=()=>document.querySelector(".site-header").classList.remove("open"));
document.querySelector("#year").textContent=new Date().getFullYear();
document.addEventListener("keydown",e=>{if(galleryDialog.open&&e.key==="ArrowRight")dialogMove(1);if(galleryDialog.open&&e.key==="ArrowLeft")dialogMove(-1)});
