// Add new outings here. The catalog, search, filters and detail views update automatically.
window.OUTINGS = [
  {id:"lake",title:"Lake Brienz by boat",type:"water",tags:["family","water","local"],badge:"Best slow day",difficulty:1,duration:1.5,distance:"Your choice",ascent:"None",season:"Apr–Oct",image:"assets/images/villa/villa-30.jpg",description:"Board a classic lake steamer in Brienz for an effortless day of turquoise coves, waterfalls and storybook villages.",route:"Brienz ferry terminal → Iseltwald or Interlaken Ost",map:"https://www.google.com/maps/search/?api=1&query=Brienz+Schiffstation"},
  {id:"ballenberg",title:"Ballenberg Open-Air Museum",type:"family",tags:["family","local"],badge:"Best rainy-day plan",difficulty:1,duration:4,distance:"Flexible",ascent:"Gentle",season:"Apr–Oct",image:"assets/images/villa/villa-14.jpg",description:"Step inside centuries of Swiss life among more than 100 historic buildings, farm animals, gardens and traditional crafts.",route:"Explore the themed museum paths at your own pace",map:"https://www.google.com/maps/search/?api=1&query=Ballenberg+Swiss+Open-Air+Museum"},
  {id:"bachalpsee",title:"First to Bachalpsee",type:"hike",tags:["hike","family"],badge:"Iconic Alpine views",difficulty:2,duration:2,distance:"6 km",ascent:"190 m",season:"Jun–Oct",image:"assets/images/villa/villa-18.jpg",description:"A broad panoramic trail from Grindelwald First reaches a mirror lake beneath the snowy Wetterhorn and Schreckhorn.",route:"First gondola station → Bachalpsee → First",map:"https://www.google.com/maps/search/?api=1&query=Bachalpsee"},
  {id:"schynige",title:"Schynige Platte Loop",type:"hike",tags:["hike","family"],badge:"Best panoramic loop",difficulty:2,duration:1.47,distance:"3.6 km",ascent:"283 m",season:"Jun–Oct",image:"assets/images/outings/schynige-platte/img_0994.jpg",description:"A compact ridge loop reached by historic cogwheel railway, with views of the Eiger, Mönch, Jungfrau and both lakes.",route:"Schynige Platte station → ridge loop → Alpine garden → station",map:"https://schweizmobil.ch/en/tour/1955112913",page:"outings/schynige-platte/"},
  {id:"eiger-wengen",title:"Eigergletscher to Wengen",type:"hike",tags:["hike","strenuous"],badge:"Best downhill traverse",difficulty:3,duration:3.15,distance:"10.9 km",ascent:"123 m",season:"Jun–Oct",image:"assets/images/outings/eigergletscher-to-wengen/img_1298.jpg",description:"Descend from glacial terrain beneath the Eiger into Alpine meadows, forests and Wengen.",route:"Eigergletscher → Wengenalp → Wengen",map:"https://schweizmobil.ch/en/tour/1373121395",page:"outings/eigergletscher-to-wengen/"},
  {id:"aare",title:"Aare Gorge & Reichenbach Falls",type:"family",tags:["family","water"],badge:"Best dramatic outing",difficulty:1,duration:3,distance:"3 km",ascent:"Minimal",season:"Apr–Nov",image:"assets/images/villa/villa-33.jpg",description:"Walk through a narrow limestone gorge, then ride the nostalgic funicular to the waterfall made famous by Sherlock Holmes.",route:"Aareschlucht West → Meiringen → Reichenbachfall funicular",map:"https://www.google.com/maps/search/?api=1&query=Aareschlucht"}
];
