// Generated by scripts/import-hikes.mjs from the folders in Downloads/hikes.
window.OUTINGS.push(...[
  {
    "id": "axalp-wooden-statue-loop",
    "title": "Axalp Wooden Statue Loop",
    "type": "hike",
    "tags": [
      "hike",
      "family",
      "local"
    ],
    "badge": "Our favorite local loop",
    "difficulty": 2,
    "duration": 2.32,
    "distance": "6 km",
    "ascent": "441 m",
    "season": "Jun–Oct",
    "image": "assets/images/outings/axalp-wooden-statue-loop/photo-01.jpg",
    "description": "Axalp is the mountain just across the lake, with amazing views of surrounding mountains you can't see down in Brienz. Hike from bus stop to a scenic mountain lake and discover wooden sculptures along the way. Great opportunity for a picnic and grill sausages at one of the fire pits.",
    "route": "Take the bus from the train station to Axalp. Driving is not recommended as the road is a single lane road with few opportunities to pass, also the bus always has the right of way. → Hike the loop. → Take the bus back to Brienz.",
    "map": "https://schweizmobil.ch/en/tour/465766232",
    "page": "outings/axalp-wooden-statue-loop/"
  },
  {
    "id": "axalp-giant-swing",
    "title": "Axalp Giant Swing",
    "type": "hike",
    "tags": [
      "hike",
      "family",
      "local"
    ],
    "badge": "Best panoramic swing",
    "difficulty": 2,
    "duration": 1.07,
    "distance": "3.2 km",
    "ascent": "64 m",
    "season": "Jun–Oct",
    "image": "assets/images/outings/axalp-giant-swing/photo-01.jpg",
    "description": "Axalp is the mountain just across the lake, with amazing views of surrounding mountains you can't see down in Brienz. Take the chairlift up, enjoy the giant swing with panoramic views and hike down through alpine meadows.",
    "route": "Take the bus from the train station to Axalp. Driving is not recommended as the road is a single lane road with few opportunities to pass, also the bus always has the right of way. → Take the chairlift up to the swing. → Hike the trail back to Axalp or if you prefer, ride the chairlift back down. → Take the bus back to Brienz.",
    "map": "https://schweizmobil.ch/en/tour/180204024",
    "page": "outings/axalp-giant-swing/"
  },
  {
    "id": "bramisegg-to-axalp",
    "title": "Bramisegg to Axalp",
    "type": "hike",
    "tags": [
      "hike",
      "local"
    ],
    "badge": "Best quiet valley",
    "difficulty": 3,
    "duration": 1.9,
    "distance": "4.2 km",
    "ascent": "555 m",
    "season": "Jun–Oct",
    "image": "assets/images/outings/bramisegg-to-axalp/photo-01.jpg",
    "description": "Beautiful hike close to home. Make sure to explore the scenic valley in the middle of the hike before you proceed to climb up to Axalp.",
    "route": "Take the bus from the train station towards Axalp and exit at the Bramisegg stop. Driving is not recommended as the road is a single lane road with few opportunities to pass, also the bus always has the right of way. → Start your hike, make sure to explore the scenic valley in the middle of the hike before you proceed to climb up to Axalp. → Take the bus back to Brienz. → If you are not tired yet, combine this hike with the \"Axalp Wooden Statue Loop\" or \"Axalp Giant Swing\" hikes.",
    "map": "https://schweizmobil.ch/en/tour/1360534567",
    "page": "outings/bramisegg-to-axalp/"
  },
  {
    "id": "brienz-rothorn",
    "title": "Brienz to Brienzer Rothorn",
    "type": "hike",
    "tags": [
      "hike",
      "strenuous",
      "local"
    ],
    "badge": "Best local challenge",
    "difficulty": 4,
    "duration": 5.35,
    "distance": "10.5 km",
    "ascent": "1775 m",
    "season": "Jun–Oct",
    "image": "assets/images/outings/brienz-rothorn/photo-01.jpg",
    "description": "Caution this is a very strenuous hike. Your reward are amazing views throughout the hike. If you prefer you can also do this hike in reverse.",
    "route": "Start your hike right from Brienz Villa. → Enjoy a beverage and snack at the restaurant at the top of Rothorn. → From the top, take the Rothorn train back to Brienz.",
    "map": "https://schweizmobil.ch/en/tour/800570378",
    "page": "outings/brienz-rothorn/"
  },
  {
    "id": "brienz-rothorn-to-brunig-pass",
    "title": "Brienzer Rothorn to Brünig Pass",
    "type": "hike",
    "tags": [
      "hike",
      "strenuous"
    ],
    "badge": "Best long descent",
    "difficulty": 4,
    "duration": 4.55,
    "distance": "12.6 km",
    "ascent": "433 m",
    "season": "Jun–Oct",
    "image": "assets/images/outings/brienz-rothorn-to-brunig-pass/photo-01.jpg",
    "description": "Caution this is a very strenuous hike. Your reward are amazing views throughout the hike. If you prefer you can also do this hike in reverse.",
    "route": "Take the Rothorn train from Brienz to Rothorn → Enjoy the views from top of Rothorn → Start your hike towards Brünig → Take the train from Brünig to Brienz",
    "map": "https://schweizmobil.ch/en/tour/1778887452",
    "page": "outings/brienz-rothorn-to-brunig-pass/"
  },
  {
    "id": "eigergletscher-to-alpiglen",
    "title": "Eigergletscher to Alpiglen",
    "type": "hike",
    "tags": [
      "hike",
      "strenuous"
    ],
    "badge": "Best Eiger close-up",
    "difficulty": 3,
    "duration": 2.03,
    "distance": "6 km",
    "ascent": "118 m",
    "season": "Jun–Oct",
    "image": "assets/images/outings/eigergletscher-to-alpiglen/photo-01.jpg",
    "description": "The Eigergletscher to Alpiglen hike—famously known as the Eiger Trail—is a stunning downhill descent in the Swiss Alps. It features sweeping valley vistas, roaring waterfalls, and a close-up walk directly beneath the sheer, legendary Eiger North Face. This hike is fantastic, but we recommend the \"Eigergletscher to Wengen\" hike if you can only do one of the two.",
    "route": "Drive to Grindelwald Terminal and park or take the train via Interlaken Ost → Take Gondola to Eigergletscher (or you can take the train to Kleine Scheidegg, then change trains) → Then start the hike along the Eiger North Face towards Grindelwald → Take train to Grindelwald → Explore Grindelwald → Drive home or take the train home",
    "map": "https://schweizmobil.ch/en/tour/607197294",
    "page": "outings/eigergletscher-to-alpiglen/"
  },
  {
    "id": "giessbach-falls-to-iseltwald",
    "title": "Giessbach Falls to Iseltwald",
    "type": "hike",
    "tags": [
      "hike",
      "family",
      "water",
      "local"
    ],
    "badge": "Best lake-and-ferry day",
    "difficulty": 2,
    "duration": 2.25,
    "distance": "7.3 km",
    "ascent": "316 m",
    "season": "Apr–Oct",
    "image": "assets/images/outings/giessbach-falls-to-iseltwald/photo-01.jpg",
    "description": "The shoreline trail is mostly flat, offering easy-going terrain and constant views of Lake Brienz. The hike concludes as you enter the picturesque, traditional fishing village of Iseltwald. As you walk into town, you will spot the iconic Seeburg Castle (Schloss Seeburg) perched out on its narrow peninsula.",
    "route": "Take the ferry from Brienz to Giessbach Falls. → Either hike up to the hotel or take the funicular. → Explore the waterfalls and views. → Return to the lakeshore and start your hike to Iseltwald → Explore Iseltwald town, famous from \"Crash Landing on You\" show → Take the ferry back to Brienz → Alternatively, If you prefer a longer voyage on Lake Brienz, take the ferry to Interlaken and return home by train.",
    "map": "https://schweizmobil.ch/en/tour/1227105142",
    "page": "outings/giessbach-falls-to-iseltwald/"
  },
  {
    "id": "grosse-scheidegg-to-first",
    "title": "Grosse Scheidegg to First",
    "type": "hike",
    "tags": [
      "hike",
      "family"
    ],
    "badge": "Best Wetterhorn views",
    "difficulty": 2,
    "duration": 1.78,
    "distance": "5.8 km",
    "ascent": "334 m",
    "season": "Jun–Oct",
    "image": "assets/images/outings/grosse-scheidegg-to-first/photo-01.jpg",
    "description": "The hike from Grosse Scheidegg to First is a highly popular, scenic panoramic trail that gives you front-row, eye-level views of the massive limestone walls of the Wetterhorn and the Bernese Alps. This hike is also a great option if you start at First and hike towards Grosse Scheidegg instead.",
    "route": "Can do this hike as a continuation of \"Rosenlaui\" hike → Alternatively, Add this hike after you visit Grindelwald First",
    "map": "https://schweizmobil.ch/en/tour/569345872",
    "page": "outings/grosse-scheidegg-to-first/"
  },
  {
    "id": "grutschalp-allmendhubel-murren",
    "title": "Grütschalp, Allmendhubel & Mürren",
    "type": "hike",
    "tags": [
      "hike",
      "family"
    ],
    "badge": "Best panoramic family day",
    "difficulty": 3,
    "duration": 2.77,
    "distance": "7.6 km",
    "ascent": "552 m",
    "season": "Jun–Oct",
    "image": "assets/images/outings/grutschalp-allmendhubel-murren/photo-01.jpg",
    "description": "The Mountain View Trail connecting Grütschalp, Allmendhubel, and Mürren is a top-class panoramic hike in the Jungfrau Region. It delivers continuous, spectacular views of the Eiger, Mönch, and Jungfrau peaks. Reaching Allmendhubel rewards you with a panoramic plateau featuring a large alpine restaurant. Families can enjoy the Flower Park adventure playground. You can also stroll along the Flower Trail, which showcases over 150 species of local mountain flora like edelweiss and gentians. From the peak, you follow a gentle, winding path down through the Blumental valley toward Mürren. This section is technically easy and behaves like a leisurely stroll down through pastures populated by grazing cows. The hike concludes in the charming village of Mürren.",
    "route": "Drive to Lauterbrunnen train station and park → Alternatively, take train to Lauterbrunnen via Interlaken Ost → Take the gondola to Grütschalp → Start your hike towards Allmendhubel → Allmendhubel has a nice restaurant for lunch and a fun playground → Continue the hike to Mürren or take the funicular → Explore the scenic town of Mürren → Take train back to Grütschalp and gondola to Lauterbrunnen → Take train or car back to Brienz",
    "map": "https://schweizmobil.ch/en/tour/1748788909",
    "page": "outings/grutschalp-allmendhubel-murren/"
  },
  {
    "id": "harder-kulm-loop",
    "title": "Harder Kulm Loop",
    "type": "hike",
    "tags": [
      "hike",
      "strenuous"
    ],
    "badge": "Best workout near Interlaken",
    "difficulty": 4,
    "duration": 4,
    "distance": "9.7 km",
    "ascent": "783 m",
    "season": "Apr–Nov",
    "image": "assets/images/outings/harder-kulm-loop/photo-01.jpg",
    "description": "The hike from Interlaken to Harder Kulm is a steep, muscle-burning forest ascent that rewards you with the absolute best bird’s-eye view of Interlaken, Lake Thun, Lake Brienz, and the snow-capped Eiger, Mönch, and Jungfrau peaks.",
    "route": "Drive to Interlaken Ost and park at the train station or take the train from Brienz → Hike up to Harderkulm → Enjoy lunch or a snack at the restaurant → Continue the loop back to Interlaken → If you dare, take a dip in the river, you deserve it → Take car or train back to Brienz",
    "map": "https://schweizmobil.ch/en/tour/1339225991",
    "page": "outings/harder-kulm-loop/"
  },
  {
    "id": "mannlichen-to-kleine-scheidegg",
    "title": "Männlichen to Kleine Scheidegg",
    "type": "hike",
    "tags": [
      "hike",
      "family"
    ],
    "badge": "Best easy Alpine panorama",
    "difficulty": 1,
    "duration": 1.15,
    "distance": "4.7 km",
    "ascent": "48 m",
    "season": "Jun–Oct",
    "image": "assets/images/outings/mannlichen-to-kleine-scheidegg/photo-01.jpg",
    "description": "The hike from Männlichen to Kleine Scheidegg—known as the Royal Walk or Panoramaweg—is one of the most famous, easy, and visually stunning high-alpine trails in Switzerland, offering uninterrupted face-to-face views of the Eiger, Mönch, and Jungfrau peaks.",
    "route": "Travel by train or car to Lauterbrunnen. Park at the train station. → Take the train up to Wengen. → Take the gondola to Männlichen. → If you travel with kids, explore the playground. → Hike to top of Männlichen to take in the views. → Hike to Kleine Scheidegg. → Take the train back to Lauterbrunnen. → Explore Lauterbrunnen → Take car or train back to Brienz",
    "map": "https://schweizmobil.ch/en/tour/1820671841",
    "page": "outings/mannlichen-to-kleine-scheidegg/"
  },
  {
    "id": "murren-allmendhubel-loop",
    "title": "Mürren & Allmendhubel Loop",
    "type": "hike",
    "tags": [
      "hike",
      "family"
    ],
    "badge": "One of our favorites",
    "difficulty": 2,
    "duration": 1.93,
    "distance": "6.4 km",
    "ascent": "204 m",
    "season": "Jun–Oct",
    "image": "assets/images/outings/murren-allmendhubel-loop/photo-01.jpg",
    "description": "One of the prettiest trails in the area, a favorite of ours. Lush meadows and stunning mountain views.",
    "route": "Drive to Stechelberg base station or take train to Lauterbrunnen then bus to Stechelberg. → Take the gondola to Mürren → Explore the scenic town of Mürren → Take funicular to Allmendhubel → Allmendhubel has a nice restaurant for lunch and a fun playground → Start the loop → Take gondola back to Stechelberg → Take train or car back to Brienz",
    "map": "https://schweizmobil.ch/en/tour/44875911",
    "page": "outings/murren-allmendhubel-loop/"
  },
  {
    "id": "brienz-to-planalp",
    "title": "Brienz to Planalp",
    "type": "hike",
    "tags": [
      "hike",
      "strenuous",
      "local"
    ],
    "badge": "Best half-day workout",
    "difficulty": 4,
    "duration": 2.67,
    "distance": "5.1 km",
    "ascent": "851 m",
    "season": "May–Oct",
    "image": "assets/images/outings/brienz-to-planalp/photo-01.jpg",
    "description": "Great hike if you are looking for a good workout starting right at the house. Get rewarded with nice views along the way.",
    "route": "Start your hike right from Brienz Villa. → From Planalp, either take the Rothorn train back to Brienz or hike back down on one of the other trails.",
    "map": "https://schweizmobil.ch/en/tour/841672674",
    "page": "outings/brienz-to-planalp/"
  },
  {
    "id": "rosenlaui-to-grosse-scheidegg",
    "title": "Rosenlaui to Grosse Scheidegg",
    "type": "hike",
    "tags": [
      "hike"
    ],
    "badge": "Best wild valley",
    "difficulty": 3,
    "duration": 1.92,
    "distance": "4.6 km",
    "ascent": "561 m",
    "season": "Jun–Oct",
    "image": "assets/images/outings/rosenlaui-to-grosse-scheidegg/photo-01.jpg",
    "description": "Hike through a lush and scenic alpine valley. The path transitions from shaded forest into wide, lush pastures. You will pass through Schwarzwaldalp, a hamlet featuring a historic water-powered sawmill and a mountain restaurant. As you make the final, steeper push toward the pass, the terrain opens up completely. You are treated to massive, up-close views of the jagged Engelhörner peaks and the sheer limestone face of the Wetterhorn. The hike concludes at Grosse Scheidegg (1,962 meters), a spectacular ridge separating the Meiringen and Grindelwald valleys. From the summit, you can enjoy panoramic views of the famous Eiger mountain.",
    "route": "From Brienz, take the train to Meiringen → From Meiringen take the bus to Rosenlaui → Exit at Schwarzwaldalp (final stop of this bus) → Hike to Grosse Scheidegg → Enjoy lunch or a snack at the restaurant → To return you have several options: → Continue with the \"Grosse Scheidegg to First\" hike, take the Gondola to Grindelwald and return by train to Brienz. → Take the bus to Grindelwald, explore the town and return by train to Brienz. → Take the bus back to Schwarzwaldalp, then Meiringen. → Hike to Grindelwald",
    "map": "https://schweizmobil.ch/en/tour/2065787092",
    "page": "outings/rosenlaui-to-grosse-scheidegg/"
  }
]);
